// Code generated by protoc-gen-go.
// source: pay.proto
// DO NOT EDIT!

/*
Package pay is a generated protocol buffer package.

It is generated from these files:
	pay.proto

It has these top-level messages:
	NoArgs
	NoReply
	MsgRes
	MsgArg
*/
package pay

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type NoArgs struct {
}

func (m *NoArgs) Reset()                    { *m = NoArgs{} }
func (m *NoArgs) String() string            { return proto.CompactTextString(m) }
func (*NoArgs) ProtoMessage()               {}
func (*NoArgs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NoReply struct {
}

func (m *NoReply) Reset()                    { *m = NoReply{} }
func (m *NoReply) String() string            { return proto.CompactTextString(m) }
func (*NoReply) ProtoMessage()               {}
func (*NoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MsgRes struct {
	ErrorCode int32 `protobuf:"varint,1,opt,name=errorCode" json:"errorCode,omitempty"`
}

func (m *MsgRes) Reset()                    { *m = MsgRes{} }
func (m *MsgRes) String() string            { return proto.CompactTextString(m) }
func (*MsgRes) ProtoMessage()               {}
func (*MsgRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MsgArg struct {
	Operation int32   `protobuf:"varint,1,opt,name=operation" json:"operation,omitempty"`
	UserId    int64   `protobuf:"varint,2,opt,name=userId" json:"userId,omitempty"`
	OrderId   string  `protobuf:"bytes,3,opt,name=orderId" json:"orderId,omitempty"`
	Money     float64 `protobuf:"fixed64,4,opt,name=money" json:"money,omitempty"`
}

func (m *MsgArg) Reset()                    { *m = MsgArg{} }
func (m *MsgArg) String() string            { return proto.CompactTextString(m) }
func (*MsgArg) ProtoMessage()               {}
func (*MsgArg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*NoArgs)(nil), "pay.NoArgs")
	proto.RegisterType((*NoReply)(nil), "pay.NoReply")
	proto.RegisterType((*MsgRes)(nil), "pay.MsgRes")
	proto.RegisterType((*MsgArg)(nil), "pay.MsgArg")
}

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x48, 0xac, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x06, 0x32, 0x95, 0x38, 0xb8, 0xd8, 0xfc, 0xf2, 0x1d,
	0x8b, 0xd2, 0x8b, 0x95, 0x38, 0xb9, 0xd8, 0xfd, 0xf2, 0x83, 0x52, 0x0b, 0x72, 0x2a, 0x95, 0xa4,
	0xb9, 0xd8, 0x7c, 0x8b, 0xd3, 0x83, 0x52, 0x8b, 0x85, 0x04, 0xb9, 0x38, 0x53, 0x8b, 0x8a, 0xf2,
	0x8b, 0x9c, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x95, 0xbc, 0xc1, 0x92, 0x40,
	0x2d, 0x20, 0xc9, 0xfc, 0x82, 0xd4, 0xa2, 0xc4, 0x92, 0xcc, 0xfc, 0x3c, 0x88, 0xa4, 0x10, 0x1f,
	0x17, 0x5b, 0x69, 0x71, 0x6a, 0x91, 0x67, 0x8a, 0x04, 0x13, 0x90, 0xcf, 0x2c, 0xc4, 0xcf, 0xc5,
	0x9e, 0x5f, 0x94, 0x02, 0x16, 0x60, 0x06, 0x0a, 0x70, 0x0a, 0xf1, 0x72, 0xb1, 0xe6, 0xe6, 0xe7,
	0xa5, 0x56, 0x4a, 0xb0, 0x00, 0xb9, 0x8c, 0x49, 0x6c, 0x60, 0xa7, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x21, 0x92, 0xb6, 0x26, 0x97, 0x00, 0x00, 0x00,
}
